AWSTemplateFormatVersion: '2010-09-09'
Parameters:
  PublicBucketName:
    Description: 'Optional name of the website bucket.'
    Type: String
    Default: ''

Mappings:
  Region2S3WebsiteSuffix:
    us-east-1:
      Suffix: .s3-website-us-east-1.amazonaws.com
    us-west-1:
      Suffix: .s3-website-us-west-1.amazonaws.com
    us-west-2:
      Suffix: .s3-website-us-west-2.amazonaws.com
    eu-west-1:
      Suffix: .s3-website-eu-west-1.amazonaws.com
    ap-northeast-1:
      Suffix: .s3-website-ap-northeast-1.amazonaws.com
    ap-northeast-2:
      Suffix: .s3-website-ap-northeast-2.amazonaws.com
    ap-southeast-1:
      Suffix: .s3-website-ap-southeast-1.amazonaws.com
    ap-southeast-2:
      Suffix: .s3-website-ap-southeast-2.amazonaws.com
    ap-south-1:
      Suffix: .s3-website-ap-south-1.amazonaws.com
    us-east-2:
      Suffix: .s3-website-us-east-2.amazonaws.com
    sa-east-1:
      Suffix: .s3-website-sa-east-1.amazonaws.com
    cn-north-1:
      Suffix: .s3-website.cn-north-1.amazonaws.com.cn
    eu-central-1:
      Suffix: .s3-website.eu-central-1.amazonaws.com
    eu-west-2:
      Suffix: .s3-website.eu-west-2.amazonaws.com
    eu-north-1:
      Suffix: .s3-website.eu-north-1.amazonaws.com

Conditions:
  HasPublicBucketName: !Not [!Equals [!Ref PublicBucketName, '']]

Resources:
  S3BucketForWebsiteContent:
    Type: 'AWS::S3::Bucket'
    Properties:
      BucketName: !If [HasPublicBucketName, !Ref PublicBucketName, !Ref 'AWS::NoValue']
      WebsiteConfiguration:
        IndexDocument: index.html
        ErrorDocument: error.html
 
  BucketPolicyPublic:
    Type: 'AWS::S3::BucketPolicy'
    Properties:
      Bucket: !Ref 'S3BucketForWebsiteContent'
      PolicyDocument:
        Statement:
        - Principal: '*'
          Action: 's3:GetObject'
          Effect: Allow
          Resource: !Sub '${S3BucketForWebsiteContent.Arn}/*'
  
Outputs:
    StackName:
      Description: 'Stack name.'
      Value: !Sub '${AWS::StackName}'
    WebsiteBucketName:
      Description: 'Name of the website bucket'
      Value: !Ref S3BucketForWebsiteContent
    DomainName:
      Description: 'Web site domain name'
      Value: !Join ['', [!Ref 'S3BucketForWebsiteContent', !FindInMap [Region2S3WebsiteSuffix,
                !Ref 'AWS::Region', Suffix]]]
